### ISSUE TITLE
pry-remote-em client quits from control+c

### ISSUE THREAD

**Issue by TreyLawrence** [gruis/pry-remote-em#38]
control+c halts the pry-remote-em process. It would be nice for it to instead quit a multi-line input, and to have exit instead properly quit the pry-remote-em process.

**Comment by Xanders** [comment]
If you are still interested, I fixed it in my fork. You can use it with this line in the Gemfile:
`gem 'pry-remote-em', git: 'https://github.com/Xanders/pry-remote-em', branch: 'a_lot_of_improvements', require: 'pry-remote-em/server'`
Please see breaking changes before:
https://github.com/Xanders/pry-remote-em/blob/a_lot_of_improvements/CHANGELOG

**Comment by Xanders** [comment]
The fix is included into 1.0.0 release, thank you!
