### ISSUE TITLE
Cannot connect remotely

### ISSUE THREAD

**Issue by baweaver** [gruis/pry-remote-em#47]
Perhaps I'm doing something odd here:

Server:

``` ruby
require 'pry-remote-em/server'
EM.run { binding.remote_pry_em 'server_ip' }
```

Client:

```
pry-remote-em pryem://server_ip
# or
pry-remote-em pryem://server_ip:6462
```

...which always throws back:

```
[pry-remote-em] session terminated
```

If I can somehow get that to work, it allows quite a few interesting things in tandem with the gems features:
- True remote debugging
  - with authentication
  - with multiple users allowed

I can already connect across a network using `pry_remote`, so if I can get this to work I can promise quite an interesting writeup of acrobatics this thing could pull off.

**Comment by Xanders** [comment]
If you're still interested in, i've created a fork with some fixes of bugs that looks like yours, maybe it will help:
https://github.com/Xanders/pry-remote-em/tree/ipv6fix
Use it in Gemfile like:
gem 'pry-remote-em', github: 'Xanders/pry-remote-em', branch: 'ipv6fix', require: 'pry-remote-em/server'
Now you can avoid an argument in binding.remote_pry_em and also in pry-remote-em shell command - that variant works for me. Then use proxy for remote hosts. But if you want to use bind address other than 127.0.0.1, I can't help, maybe my fixes also fix that.

P.S.: I'm not a maintainer. And sorry for bad English. :)

**Comment by Xanders** [comment]
@baweaver, I think, the problem was in using some special server IP on server start. Try to use '0.0.0.0' instead, and all should work as expected. If it is, search for problem in the network (if you really want to bind to one interface only).
Also you can try new 1.0.0 version with lot of bugfixes and improvements, see https://github.com/gruis/pry-remote-em/blob/master/CHANGELOG.md#100.

**Comment by Xanders** [comment]
Feel free to open a new issue if you're still have some problems.
